# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(max_length=200)),
                ('courseTutor', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId1', models.CharField(max_length=7)),
                ('courseId2', models.CharField(max_length=7)),
                ('courseId3', models.CharField(max_length=7)),
                ('courseId4', models.CharField(max_length=7)),
                ('courseId5', models.CharField(max_length=7)),
                ('courseId6', models.CharField(max_length=7, null=True)),
                ('courseId7', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(max_length=6)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('enum', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fnum', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('empid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='courseregistered',
            name='enum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clgmng.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clgmng.Teacher'),
        ),
    ]
